prompt --application/pages/page_00004
begin
--   Manifest
--     PAGE: 00004
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.5'
,p_default_workspace_id=>49061394803238251641
,p_default_application_id=>95416
,p_default_id_offset=>0
,p_default_owner=>'WKSP_WPJPAULORCTRAINING'
);
wwv_flow_api.create_page(
 p_id=>4
,p_user_interface_id=>wwv_flow_api.id(49072317651837507290)
,p_name=>'PROFESSOR_RPT'
,p_alias=>'PROFESSOR-RPT'
,p_step_title=>'PROFESSOR_RPT'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_last_updated_by=>'JPAULORC@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220321192730'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(49145802336141743312)
,p_plug_name=>'Report 1'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(49072216072106507252)
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'PROFESSOR'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_page_header=>'Report 1'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(49145802748023743312)
,p_name=>'Report 1'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:5:&SESSION.::&DEBUG.:RP:P5_ID:\#ID#\'
,p_detail_link_text=>'<span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>'
,p_owner=>'JPAULORC@GMAIL.COM'
,p_internal_uid=>49145802748023743312
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49145802876320743313)
,p_db_column_name=>'ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49145803229904743313)
,p_db_column_name=>'NOME'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Nome'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49145803650536743313)
,p_db_column_name=>'GRAU_INSTRUCAO_ID'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>unistr('Grau Instru\00E7\00E3o')
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_api.id(49146285068915412822)
,p_rpt_show_filter_lov=>'1'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49145804001384743314)
,p_db_column_name=>'DT_NASCIMENTO'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Dt Nascimento'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49145804494732743314)
,p_db_column_name=>'EMAIL'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Email'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(48821768964384732250)
,p_db_column_name=>'TELEFONE'
,p_display_order=>15
,p_column_identifier=>'F'
,p_column_label=>'Telefone'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771850541689249401)
,p_db_column_name=>'ENDERECO'
,p_display_order=>25
,p_column_identifier=>'G'
,p_column_label=>unistr('Endere\00E7o')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771850634435249402)
,p_db_column_name=>'ENDERECO_NUMERO'
,p_display_order=>35
,p_column_identifier=>'H'
,p_column_label=>unistr('N\00FAmero')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771850720212249403)
,p_db_column_name=>'COMPLEMENTO'
,p_display_order=>45
,p_column_identifier=>'I'
,p_column_label=>'Complemento'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771850809312249404)
,p_db_column_name=>'CEP'
,p_display_order=>55
,p_column_identifier=>'J'
,p_column_label=>'Cep'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771850924545249405)
,p_db_column_name=>'BAIRRO_ID'
,p_display_order=>65
,p_column_identifier=>'K'
,p_column_label=>'Bairro Id'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771851050369249406)
,p_db_column_name=>'CIDADE_ID'
,p_display_order=>75
,p_column_identifier=>'L'
,p_column_label=>'Cidade'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_api.id(49771786575575862198)
,p_rpt_show_filter_lov=>'1'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(49771851105577249407)
,p_db_column_name=>'CURRICULO'
,p_display_order=>85
,p_column_identifier=>'M'
,p_column_label=>'Curriculo'
,p_column_type=>'CLOB'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(49145832501909750947)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'491458326'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID:NOME:GRAU_INSTRUCAO_ID:DT_NASCIMENTO:EMAIL:TELEFONE:ENDERECO:ENDERECO_NUMERO:COMPLEMENTO:CEP:BAIRRO_ID:CIDADE_ID:CURRICULO'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(49145810030377746199)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(49072232484978507258)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_api.id(49072129546355507220)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_api.id(49072294502092507281)
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(49145811254619746200)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(49145802336141743312)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(49072292949459507280)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Novo'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:5:&SESSION.::&DEBUG.:5'
);
wwv_flow_api.component_end;
end;
/
