CREATE OR REPLACE PACKAGE email_k IS
    FUNCTION CHECK_EMAIL(P_EMAIL IN VARCHAR2) RETURN BOOLEAN;
    FUNCTION CREATED_EMAIL(P_ID NUMBER
                          ,P_EMAIL IN VARCHAR2) RETURN BOOLEAN;
END email_k;
/

CREATE OR REPLACE PACKAGE BODY email_k IS
    FUNCTION CHECK_EMAIL(P_EMAIL IN VARCHAR2) RETURN BOOLEAN IS
        V_EXPRESSION VARCHAR2(200);    
    BEGIN
        V_EXPRESSION := '^[a-z0-9._-]+@[a-z0-9]+\.[a-z]+(\.[a-z]+)?(\.[a-z]+)?$';
        RETURN REGEXP_LIKE(P_EMAIL, V_EXPRESSION);    
    END CHECK_EMAIL;
    
    FUNCTION CREATED_EMAIL(P_ID NUMBER
                          ,P_EMAIL IN VARCHAR2) RETURN BOOLEAN IS
        V_CONTADOR NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_CONTADOR  
          FROM professor
         WHERE UPPER(email) = UPPER(P_EMAIL)
           AND (ID != P_ID OR P_ID IS NULL);
        RETURN V_CONTADOR = 0;
    END CREATED_EMAIL;
END email_k;
/