CREATE TABLE usuario
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
   ,LOGIN VARCHAR2(100)
   ,NOME  VARCHAR2(100)
   ,SENHA VARCHAR2(100)
   ,PERFIL VARCHAR2(3)
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (ID);

CREATE OR REPLACE PACKAGE autentica_k IS
    FUNCTION autenticar (p_username IN VARCHAR2
                        ,p_password IN VARCHAR2) RETURN BOOLEAN;

    FUNCTION admin RETURN BOOLEAN;

    FUNCTION consulta RETURN BOOLEAN;

    FUNCTION cadastro RETURN BOOLEAN;
END autentica_k;
/

CREATE OR REPLACE PACKAGE BODY autentica_k IS
    FUNCTION autenticar (p_username IN VARCHAR2
                        ,p_password IN VARCHAR2) RETURN BOOLEAN IS
        v_id        NUMBER;
        v_profile   VARCHAR2(100);
        v_nome       VARCHAR2(100);
    BEGIN
        --apex_util.set_session_state(p_name => 'PO_LOGIN_MESSAGE', p_value => NULL);
        SELECT MAX(ID), MAX(PERFIL), MAX(NOME)
          INTO v_id, v_profile, v_nome
          FROM usuario
         WHERE UPPER(login) = UPPER(p_username)
           AND senha = p_password;

        IF v_id IS NULL THEN
            --apex_util.set_session_state(p_name => 'PO_LOGIN_MESSAGE', p_value => 'Usuário inválido!');
            apex_util.set_authentication_result(1);
            RETURN FALSE;
        END IF;
            --apex_util.set_session_state(p_name => 'PO_ID_USUARIO', p_value => v_id);
            --apex_util.set_session_state(p_name => 'PO_NOME_USUARIO', p_value => v_nome);
            --apex_util.set_session_state(p_name => 'PO_PERFIL', p_value => v_profile);
        apex_util.set_authentication_result(0);
        RETURN TRUE;
    END autenticar;

    FUNCTION admin RETURN BOOLEAN IS
    BEGIN
        RETURN v('PO_PERFIL') = 'ADM';
    END admin;

    FUNCTION consulta RETURN BOOLEAN IS
    BEGIN
        RETURN v('PO_PERFIL') = 'CON';
    END consulta;

    FUNCTION cadastro RETURN BOOLEAN IS
    BEGIN
        RETURN v('PO_PERFIL') = 'CAD';
    END cadastro;
END autentica_k;
/

