ALTER TABLE professor ADD TELEFONE          VARCHAR2(20);
ALTER TABLE professor ADD ENDERECO          VARCHAR2(50);
ALTER TABLE professor ADD ENDERECO_NUMERO   VARCHAR2(10);
ALTER TABLE professor ADD COMPLEMENTO       VARCHAR2(30);
ALTER TABLE professor ADD CEP               VARCHAR2(8);
ALTER TABLE professor ADD BAIRRO_ID         NUMBER;
ALTER TABLE professor ADD CIDADE_ID         NUMBER;
ALTER TABLE professor ADD CURRICULO         CLOB;